services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: esir_vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./vw-data:/data         # stockage des mots de passes (aucune id√©e ce si c'est une bonne pratique)
    networks:
      - esir-network

networks:
  esir-network:
    external: true