services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: esir_rocketchat
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.komquest.cc
      - MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?directConnection=true
    depends_on:
      - mongo
    networks:
      - esir-network

  mongo:
    image: mongo:4.4
    container_name: esir_mongo
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    networks:
      - esir-network

  mongo-init-replica:
    image: mongo:4.4
    command: >
      bash -c "for i in `seq 1 30`; do
          mongo --host mongo --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"localhost:27017\" } ] })' &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
    networks:
      - esir-network

networks:
  esir-network:
    external: true