services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.4.8
    container_name: esir_rocketchat
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.komquest.cc
      - MONGO_URL=mongodb://esir_mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://esir_mongo:27017/local?replicaSet=rs0&directConnection=true
    depends_on:
      - mongo
      - mongo-init-replica
    ports:
      - "3000:3000"
    networks:
      - esir-network

  mongo:
    image: mongo:4.4
    container_name: esir_mongo
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    networks:
      - esir-network

  mongo-init-replica:
    image: mongo:4.4
    container_name: esir_mongo_init
    command: >
      bash -c "for i in `seq 1 30`; do
          mongo --host mongo --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"mongo:27017\" } ] })' && break;
          mongo --host mongo --eval 'if (rs.status().ok) quit(0); else quit(1)' && break;
          echo \"En attente de Mongo... (Tentative $i)\";
          sleep 5;
        done; exit 0"
    depends_on:
      - mongo
    networks:
      - esir-network

networks:
  esir-network:
    external: true
