services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: esir_rocketchat
    restart: unless-stopped
    command: >
      bash -c "for i in `seq 1 30`; do
        node main.js &&
        s=$$? && break || s=$$?;
        echo \"Tried $$i times. Waiting 5 secs...\";
        sleep 5;
      done; (exit $$s)"
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.komquest.cc
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    networks:
      - esir-network

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: esir_mongo
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    networks:
      - esir-network

  # auto db config
  mongo-init-replica:
    image: mongodb/mongodb-community-server:6.0-ubi8
    command: >
      bash -c "for i in `seq 1 30`; do
          mongosh --host mongo --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"localhost:27017\" } ] })' &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
    networks:
      - esir-network

networks:
  esir-network:
    external: true