services:
  reverse-proxy:
    image: nginx:latest
    container_name: esir_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - esir-network

networks:
  esir-network:
    external: true