services:
  reverse-proxy:
    image: nginx:latest
    container_name: esir_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - esir-network

networks:
  esir-network:
    external: true