services:
  vocechat:
    image: privoce/vocechat-server:latest
    container_name: esir_vocechat
    restart: unless-stopped
    volumes:
      - ./data:/home/vocechat-server/data
    networks:
      - esir-network
    ports:
      - "3009:3000" # 3000 déjà sur gitea

networks:
  esir-network:
    external: true