services:
  db:
    image: postgres:16-alpine
    container_name: esir_mm_db
    restart: unless-stopped
    volumes:
      - mm_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mattermost
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
    networks:
      - default

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: esir_mattermost
    restart: always
    depends_on:
      - db
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://chat.test.local
    volumes:
      - ./mm_data:/mattermost/data
    networks:
      - esir-network
      - default

networks:
  esir-network:
    external: true


volumes:
  mm_db_data: